M48
; DRILL file {KiCad 7.0.1} date Sun Nov 26 12:32:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-26T12:32:25+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0827
%
G90
G05
T1
X6.5681Y-3.5715
T2
X5.0705Y-2.8494
X5.0705Y-3.8337
X7.0406Y-2.8494
T3
X7.0406Y-3.8337
T0
M30
